name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Publish Distribution ZIP
        uses: actions/upload-artifact@v2
        with:
          name: syscan.zip
          path: build/distributions/syscan.zip
      - name: Publish Shadow JAR
        uses: actions/upload-artifact@v2
        with:
          name: syscan-all.jar
          path: build/libs/syscan-all.jar
